### ISSUE TITLE
Add reference field to YAML input files

### ISSUE THREAD

**Issue by ischoegl** [Cantera/enhancements#15]
**Abstract**

A `reference` field would clarify the provenance of YAML files beyond what is included in the `decription` field, which is automatically generated from chemkin input (but is missing for many YAML files in 2.5.0a3). An implementation could use a single BibTeX entry as input, which is reformatted into YAML, e.g.

```yaml
reference:
  - title: GRI-Mech 3.0
  - author: [G. P. Smith, D. M. Golden, M. Frenklach, N. W. Moriarty, B. Eiteneer, M. Goldenberg, C. T. Bowman, R. K. Hanson, S. Song, W. C. Gardiner, Jr., V. V. Lissianski, Z. Qin]
  - year: 1999
  - howpublished: http://www.me.berkeley.edu/gri_mech/
``` 

**Motivation**

While some input files (e.g. `gri30.yaml`) do use the `description` tag, others do not (e.g. `nDodecane_Reitz.yaml`, `h2o2.yaml`, `nasa.yaml`, `gri30_highT.yaml`). In many cases, it is not clear where input originates (i.e. are they peer-reviewed? is this just a file compiled for demonstration purposes?) 

If available, a chemkin header block does not use consistent content. Content pulled from a BibTeX entry would resolve this shortcoming.

Describe the need for the proposed change:

This feature request proposes a mechanism to address Cantera/cantera#339; further: the BibTeX `comment` field can be used to add context.

**Possible Solutions**

The proposed solution would be to generate information from a single BibTeX entry, which is passed as an input file via a `--bibtex=` option to `ck2yaml`. The BibTeX fields can be converted to yaml fields with little effort.

**References**

* Cantera/cantera#339
* Discussion of `comment` field in Cantera/cantera#768
