### ISSUE TITLE
Revise YAML species definitions to support multiple thermo models

### ISSUE THREAD

**Issue by speth** [Cantera/enhancements#20]
**Abstract**

The aim of this enhancement is to improve the organization of thermo data within YAML "species" entries to allow better re-use with multiple phase thermo models and simplify serialization. Comments on the possible solutions would be greatly appreciated.

**Motivation**

Two problematic cases have been identified with how the species entries are currently organized. One comes from a discussion on Cantera/cantera#641 about how to store model-specific parameters for multiple models (i.e. Redlich-Kwong and Peng-Robinson coefficients) with a single species definition. The other was one I noticed while working on the implementation of #11, which is that (a) species data needed by the `ThermoPhase` is *almost* always in the `equation-of-state` field, with the exception of several fields used in the Debye-Huckel model and (b) we are using the `equation-of-state` field both for setting up `ThermoPhase` objects and for setting up `PDSS` objects.

Two species definitions for illustration:
```yaml
- name: H2  # species for Redlich-Kwong phase
  composition: {H: 2}
  thermo:
    model: NASA7
    temperature-ranges: [200.0, 1000.0, 3500.0]
    data:
    - [2.34433112, 0.00798052075, -1.9478151e-05, 2.01572094e-08, -7.37611761e-12,
      -917.935173, 0.683010238]
    - [3.3372792, -4.94024731e-05, 4.99456778e-07, -1.79566394e-10, 2.00255376e-14,
      -950.158922, -3.20502331]
  equation-of-state:
    model: Redlich-Kwong
    units: {length: cm, pressure: bar, quantity: mol}
    a: [3.0e+08, -3.30e+06]
    b: 31.0
- name: NaCl(aq)  # species for Debye-Huckel phase
  composition: {Na: 1, Cl: 1}
  thermo:
    model: piecewise-Gibbs
    h0: -96.03E3 cal/mol
    dimensionless: true
    data: {298.15: -174.5057463, 333.15: -174.5057463}
  equation-of-state:
    model: constant-volume
    molar-volume: 1.3
  electrolyte-species-type: weak-acid-associated  # top-level field used only by Debye-Huckel
  weak-acid-charge: -1.0  # top-level field used only by Debye-Huckel
```

**Possible Solutions**

There are several possible solutions, with different pros and cons. In the examples below, the `thermo` field for each species has been elided for simplicity.

*Update*: Based on the discussion with @ischoegl some of the pros/cons have been updated, and a 4th option has been introduced. I think the newly-introduced **Option 4** is my current preference.

**Option 1**: Allow `equation-of-state` to be a list, and put all phase-specific thermo data an entry in this list
```yaml
- name: H2  # species for Redlich-Kwong phase
  composition: {H: 2}
  equation-of-state:
  - model: Redlich-Kwong
    units: {length: cm, pressure: bar, quantity: mol}
    a: [3.0e+08, -3.30e+06]
    b: 31.0
  - model: Peng-Robinson
    units: {length: cm, pressure: bar, quantity: mol}
    a: [2.1e+08, -4.50e+06]
    b: 27.0
- name: NaCl(aq)  # species for Debye-Huckel phase
  composition: {Na: 1, Cl: 1}
  equation-of-state:
  - model: constant-volume
    molar-volume: 1.3
  - model: Debye-Huckel
    electrolyte-species-type: weak-acid-associated
    weak-acid-charge: -1.0
```

*Pros*:
- No change required for species with only a single `equation-of-state` field
- Suggests a parallel route to enabling multiple sets of species transport data

*Cons*:
- Implementation complexity due to intermingling of data for setting up both `ThermoPhase` and `PDSS` models, and due to the fact that the `equation-of-state` field can be either a map or a list of maps.
- Introduces strange behavior for the Debye-Huckel model, where two `equation-of-state` entries are used simultaneously
- Mis-categorizes Debye-Huckel species thermo data, which isn't really used to define the equation of state

**Option 2**: Make `equation-of-state` a map of maps
```yaml
- name: H2  # species for Redlich-Kwong phase
  composition: {H: 2}
  equation-of-state:
    Redlich-Kwong:
      units: {length: cm, pressure: bar, quantity: mol}
      a: [3.0e+08, -3.30e+06]
      b: 31.0
    Peng-Robinson:
      units: {length: cm, pressure: bar, quantity: mol}
      a: [2.1e+08, -4.50e+06]
      b: 27.0
- name: NaCl(aq)  # species for Debye-Huckel phase
  composition: {Na: 1, Cl: 1}
  equation-of-state:
    constant-volume:
      molar-volume: 1.3
    Debye-Huckel:
      electrolyte-species-type: weak-acid-associated
      weak-acid-charge: -1.0
```

*Pros*:
- Simpler implementation than option 1 due to consistent data structure

*Cons*:
- Introduces an extra layer of nesting required, even though for most species there will only be one item in `equation-of-state` map.
- Inconsistent with the current structure of the `transport` and `thermo` nodes
- Requires changes to all existing files that use the `equation-of-state` field
- Introduces strange behavior for the Debye-Huckel model, where two `equation-of-state` entries are used simultaneously
- Mis-categorizes Debye-Huckel species thermo data, which isn't really used to define the equation of state

**Option 3**: Use `equation-of-state` only for `PDSS` setup, and use a per-model top level field for phase-specific data
```yaml
- name: H2  # species for Redlich-Kwong phase
  composition: {H: 2}
  Redlich-Kwong:
    units: {length: cm, pressure: bar, quantity: mol}
    a: [3.0e+08, -3.30e+06]
    b: 31.0
  Peng-Robinson:
    units: {length: cm, pressure: bar, quantity: mol}
    a: [2.1e+08, -4.50e+06]
    b: 27.0
- name: NaCl(aq)  # species for Debye-Huckel phase
  composition: {Na: 1, Cl: 1}
  equation-of-state:
    model: constant-volume
    molar-volume: 1.3
  Debye-Huckel:
    electrolyte-species-type: weak-acid-associated
    weak-acid-charge: -1.0
```
*Pros*: 
- Separation of `ThermoPhase` and `PDSS` parameters makes implementation straightforward

*Cons*:
- Requires changes for some existing files (mostly those using these two phase models)
- Equation of state data ends up specified in two different ways depending on what should be considered an implementation detail (whether or not the phase uses the `PDSS` model)

**Option 4**: Allow lists in the `equation-of-state` section for multiple sets of equation of state parameters, of which one will be used with a particular phase. Create a new top-level key for Debye-Huckel parameters. This is a mix of options 1 and 3.
```yaml
- name: H2  # species for Redlich-Kwong phase
  composition: {H: 2}
  equation-of-state:
  - model: Redlich-Kwong
    units: {length: cm, pressure: bar, quantity: mol}
    a: [3.0e+08, -3.30e+06]
    b: 31.0
  - model: Peng-Robinson
    units: {length: cm, pressure: bar, quantity: mol}
    a: [2.1e+08, -4.50e+06]
    b: 27.0
- name: NaCl(aq)  # species for Debye-Huckel phase
  composition: {Na: 1, Cl: 1}
  equation-of-state:
  - model: constant-volume
    molar-volume: 1.3
  Debye-Huckel:
    electrolyte-species-type: weak-acid-associated
    weak-acid-charge: -1.0
```
*Pros*:
* Allows equation of state parameters compatible with different thermo models, stored in a consistent location regardless of the thermo model type

*Cons*:
* Some implementation complexity required to allow `equation-of-state` to be either a map or a list of maps.
* Debye-Huckel parameters are still unique in using a top-level field of their own in the species definition

**Comment by ischoegl** [comment]
I'm not sure that the differentiation between `PDSS` (pressure dependent standard state) and `ThermoPhase` is sufficiently clear, as the former is just an aspect of the latter? I.e. **Option 2** (or the less readable **Option 1**) would make more sense for users that are not familiar with 'under-the-hood' implementations. Without knowing the context, **Option 3** is honestly confusing as it mixes two notations and is not consistent: at least in the [YAML phase documentation](https://testing.cantera.org/tutorials/yaml/phases.html), `Debye-Huckel` is just another thermo phase, so it should be an alternative to `constant-volume`, and stand on its own ...

As an aside, it is not clear why the current implementation uses top-level entries `electrolyte-species-type`, `weak-acid-charge`, `ionic-radius` for a specific `ThermoPhase` implementation (see [YAML species documentation](https://testing.cantera.org/tutorials/yaml/yaml-species.html)). Shouldn't those be part of a `Debye-Huckel` entry in `equation-of-state`, as suggested in Options 1 and 2?

**Comment by speth** [comment]
> I'm not sure that the differentiation between `PDSS` (pressure dependent standard state) and `ThermoPhase` is sufficiently clear, as the former is just an aspect of the latter?

I find that there's very little that's actually clear when it comes to the `PDSS` classes in Cantera. `PDSS` models apply to individual species, and each species in a phase can use a different `PDSS` model. At least some of the `PDSS` models can be used with multiple different `ThermoPhase` models (of the ones derived from the `VPStandardState` class). It's important to retain the ability to mix and match these models. 

I had hoped that the name `equation-of-state` for the YAML field would be more helpful than `pressure-dependent-standard-state`, since in many instances, there is no pressure dependence, e.g. for constant volume species. Of course, things get a bit confused once you recognize that there are species where we have additional data needed to define their equation of state but the corresponding `ThermoPhase` doesn't use `PDSS` objects at all (i.e. Redich-Kwong).

> `Debye-Huckel` is just another thermo phase, so it should be an alternative to `constant-volume`, and stand on its own ... ?

The `DebyeHuckel` `ThermoPhase` class needs each species to have a `PDSS` model in order to get density information, which it gets from the `constant-volume` model in this example, but could be something else like `density-temperature-polynomial`. This phase *also* requires some additional species-specific information, which is does not apply to any particular `PDSS` model.

> **Option 3** is honestly confusing as it mixes two notations and is not consistent

The two different notations is kind of the point of this option. The `equation-of-state` field specifies one of several `PDSS` models, which should be used for any phase (at least, any of the ones derived from `VPStandardStateTP`). The other top-level fields may be used depending on the phase thermo model.

> As an aside, it is not clear why the current implementation uses top-level entries `electrolyte-species-type`, `weak-acid-charge`, `ionic-radius` for an otherwise specific `ThermoPhase` implementation (`Debye-Huckel`, see [YAML species documentation](https://testing.cantera.org/tutorials/yaml/yaml-species.html)). Shouldn't those be part of a `Debye-Huckel` entry in `equation-of-state`, as suggested in Options 1 and 2?

Changing the location of these fields is one of the two main points of this enhancement proposal.

> **PS:** there may be an Option 4, which eliminates the `equation-of-state` field in favor of per-model top level fields only (similar to Option 3, but shifting `constant-volume` up by one level).

This would make it difficult to create `PDSS` objects using the factory pattern, since you wouldn't know which top-level field of the species entry was the appropriate one. This issue also affects Options 1 and 2, to a lesser extent. And of course, I meant to say that suggestions for alternative structures are welcome.

**Comment by ischoegl** [comment]
@speth ... your explanations confirm some of my suspicions (especially regarding `Debye-Huckel`). 

> The `DebyeHuckel` `ThermoPhase` class needs each species to have a `PDSS` model in order to get density information, [...]

... would it make sense to merge `PDSS` information into the `Debye-Huckel` entry (they're not supposed to be alternate models). I.e. 

```yaml
- name: NaCl(aq)  # species for Debye-Huckel phase
  composition: {Na: 1, Cl: 1}
  Debye-Huckel:
    equation-of-state: 
      model: constant-volume
      molar-volume: 1.3
    electrolyte-species-type: weak-acid-associated
    weak-acid-charge: -1.0
```
which would work as long as there aren't multiple `PDSS` specifications in the same file (not sure whether the current YAML approach would allow for this).

**Comment by speth** [comment]
An `equation-of-state` field is needed not just for the Debye-Huckel model, though, but to use this species definition with any phase model derived from `VPStandardStateTP`. I think this structure would make it difficult to instantiate the `PDSS` object in a suitably generic location in the code. What would you do with the `equation-of-state` fields for all of the other phase types that use `PDSS` objects?

**Comment by ischoegl** [comment]
@speth ... what I suggested above was mostly in direct response to your explanation. I was also thinking about how things are instantiated from the UI (the user implicitly specifies `ThermoPhase` by selecting a phase name from the YAML input file, which would be `Debye-Huckel`, see `debye-huckel-B-dot-ak` in `thermo-models.yaml`): from that perspective, `PDSS` would be selected via the `Debye-Huckel` switch. 

```yaml
- name: NaCl(aq)  # species for Debye-Huckel phase
  composition: {Na: 1, Cl: 1}
  Debye-Huckel:
    equation-of-state: 
      model: constant-volume
      molar-volume: 1.3 
    electrolyte-species-type: weak-acid-associated
    weak-acid-charge: -1.0
  # other CPStandardStateTP derived phase models
```
I acknowledge that there may be redundant `equation-of-state` entries, but imho it is more important to create a clear input structure.

**Comment by speth** [comment]
So if you wanted to use this species definition with additional phase thermo models, you would have to add a new section to the species definition for each of them, even if all they required was the specification of a constant molar volume? That loses the level of reusability that even the current structure has. I think it's more likely to want to be able to re-use the same `PDSS` model with multiple phase thermo models than it is to want a different `PDSS` model for each phase model (and if that is needed, there's always the option of having a completely separate species definition). 

My question about the other phase types that use PDSS models was mainly concerned with the fact that with the exception of Debye-Huckel, the other models that use `PDSS` species do not require any additional species-specific parameters. So you'd end up with what seems like an unnecessary extra level of nesting:
```yaml
- name: KCl(l)
  composition: {K: 1, Cl: 1}
  Margules:
    equation-of-state:
      model: constant-volume
      molar-volume: 37.57 cm^3/gmol
```
This structure also makes it more difficult to construct the `PDSS` object for the species, since we don't know where the `equation-of-state` field is unless we have the `ThermoPhase` object on hand and can query it, and then we can only (easily) specify one place to look. In contrast, the current initialization code only needs to check that the phase is a `VPStandardStateTP` and then the correct `PDSS` object can be created directly.

I should also clarify that I don't think that these top-level sections should necessarily be paired 1 to 1 with phase `thermo` models. For instance, it might be useful to allow a `critical-state` field that contains the critical temperature and pressure, which could then be used to determine Redlich-Kwong or Peng-Robinson parameters if model-specific coefficients are not given.
