### ISSUE TITLE
Formalize YAML metadata fields

### ISSUE THREAD

**Issue by ischoegl** [Cantera/enhancements#56]
**Abstract**

Based on a discussion in Cantera/cantera#881, the description of metadata appears to not be fully formalized. At the moment, `ck2yaml` creates `note` and `description` fields. See @speth's comment

> Just because `ck2yaml` currently creates a field named `note` doesn't mean should formalize that as the way of storing metadata. I know there are multiple pseudo-standards for organizing metadata in Chemkin mechanism comments which could be used to populate more semantically useful fields. For example, I know RMG puts the SMILES for each species as the comment following each species name in the SPECIES section, and information on the source of the reaction rate before each reaction. If `ck2yaml` gets smart enough to do this, I'd rather the `note` field be empty except when it doesn't know what else to do.

**Motivation**

Defining `note` and `description` now with potentially moving to other ways of storing metadata in the future will create potential issues in terms of backward compatibility.  At the moment, `note` contains CHEMKIN comments that qualify as metadata if the YAML file is generated by `ck2yaml`. I.e. if someone uses a YAML file generated by `ck2yaml` in 2.5, and then revisits a problem in, say, 3.1, the YAML `note` fields should still be supported/readable? I strongly believe that once `ck2yaml` creates a precedent of defining specific fields it will be difficult to change in future releases.

With Cantera 2.5 still in alpha stage, there's a (rapidly closing) window of opportunity to 'future-proof' metadata fields by renaming `note` and `description` to `meta` and treating them as a generic `AnyValue` fields. It thus can be a string (as in the current implementation) for 2.5 or any other structure down the road.

**Possible Solutions**

Rename `note` and `description` to `meta` in YAML files (`sed` replacements in current YAML data), update converters and parsers.

**References**

- Cantera/cantera#881
- Cantera/enhancements#52

**Comment by speth** [comment]
I don't really see what problem this is solving. Can you give an example of what you think would go in the `meta` field, and how that's not supported by the current implementation? My thinking has generally been that we should support unrestricted user-defined fields within at least all of the higher-level YAML data structures.

To avoid creating backwards incompatibilities in the example I gave, I think it would be reasonable for that additional comment-parsing behavior of `ck2yaml` to be a (non-default) option.

**Comment by ischoegl** [comment]
> I don't really see what problem this is solving. Can you give an example of what you think would go in the `meta` field, and how that's not supported by the current implementation? 

The way I see this, `note` (as well as `description`) already constitute metadata, which just happens to be the version that `ck2yaml` currently understands. If future versions of `ck2yaml` would interpret annotations differently (or use different field names in default and non-default behavior), this would mean that `note`s would all of a sudden be empty, while a previously non-existent `meta` is populated. My point is that it may be more consistent to create a `meta` field from the get go, which can be  populated using a `str` (current behavior), or some other structure (non-default behavior of future versions).

From a user perspective, this would mean that `<ctobject>.meta` would *always* produce a result, whereas in the default/non-default version you describe, one or even both would not exist (i.e. it could be `<ctobject>.note` or `<ctobject>.meta` or neither exists); I believe that it's less confusing to always have `meta` defined (i.e. as a standard attribute), and just have it return `None` if nothing had been specified.

**Comment by ischoegl** [comment]
**PS:** I haven't given an actual example of YAML input yet. Keeping with the definition of `meta` being *data describing data* (as opposed to auxiliary data), this would be a possibility:
```
species:
- name: H2
  composition: {H: 2}
  meta:
    alias: hydrogen
    smiles: [HH]
    InChI: InChI=1S/H2/h1H
    inChIKey: UFHFLCQGNIYNRP-UHFFFAOYSA-N
  thermo:
    model: NASA7
    temperature-ranges: [200.0, 1000.0, 3500.0]
    data:
    - [2.34433112, 7.98052075e-03, -1.9478151e-05, 2.01572094e-08, -7.37611761e-12,
      -917.935173, 0.683010238]
    - [3.3372792, -4.94024731e-05, 4.99456778e-07, -1.79566394e-10, 2.00255376e-14,
      -950.158922, -3.20502331]
    meta: TPIS78
[...]

reactions:
- equation: 2 H + H2 <=> 2 H2  # Reaction 40
  rate-constant: {A: 9.0e+16, b: -0.6, Ea: 0.0}
  meta: some description
[...]
```
I.e. `meta` mostly replaces `note` (anticipated use for Cantera 2.5). For `H2`, I have added a meta field with hierarchical structure, as a mock-up for potential Cantera 2.6+ implementations (using data from [PubChem](https://pubchem.ncbi.nlm.nih.gov/compound/783)). Note that this naturatlly combines with #14 as *data describing data*.
